name: AutoDeploy
on:
    push:
        branches:
            - "aws/**"

permissions:
  id-token: write
  contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Git clone the repository
              uses: actions/checkout@v1

            - name: register variables
              id: setregion
              run: |
                  echo "::set-output name=aws-region::$(./bin/github_actions.py region)"

            - name: Configure aws credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE }}
                  aws-region: ${{ steps.setregion.outputs.aws-region }}

            - uses: actions/setup-node@v2
              with:
                  node-version: "14"

            - name: Run Deploy
              run: ./bin/github_actions.py deploy --doit
